/* eslint-disable prettier/prettier */
export const URL_SERVER = 'http://localhost:5000/api';

export const SAVE_FILE = {
  DGN_FILE: '../DATA_BUILD/',
};

export const STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};


export const MA_DAT = [
  {
    id: 1,
    name: 'Đất ở tại nông thôn',
    ma: 'ONT',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 208, 255)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 2,
    name: 'Đất ở tại đô thị',
    ma: 'ODT',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 160, 255)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 3,
    name: 'Đất trồng cây lâu năm',
    ma: 'CLN',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: '#ffd2a0',
      borderColor: 'rgb(255,210,160)',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 4,
    name: 'Đất ở',
    ma: 'OTC',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 180, 255)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 5,
    name: 'Đất nông nghiệp',
    ma: 'NNP',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,255,100)',
      borderColor: '#616161',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 6,
    name: 'Đất sản xuất nông nghiệp',
    ma: 'SXN',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,252,110)',
      borderColor: '#616161',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 7,
    name: 'Đất trồng cây hàng năm',
    ma: 'CHN',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,252,120)',
      borderColor: '#616161',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  // {
  //   id: 8,
  //   name: 'Đất trồng cây hàng năm',
  //   ma: 'NNP',
  //   styles: {
  //     width: 70,
  //     paddingVertical: 15,
  //     backgroundColor: 'rgb(255,252,120)',
  //     borderColor: '#616161',
  //     borderWidth: 0.5,
  //     borderRadius: 5,
  //     marginRight: 5,
  //     alignItems: 'center',
  //     justifyContent: 'center',
  //   },
  // },
  {
    id: 9,
    name: 'Đất trồng lúa',
    ma: 'LUA',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,252,130)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 10,
    name: 'Đất chuyên trồng lúa nước',
    ma: 'LUC',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,252,140)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 11,
    name: 'Đất trồng lúa nước còn lại',
    ma: 'LUK',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,252,150)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 12,
    name: 'Đất trồng lúa nương',
    ma: 'LUN',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,252,180)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 13,
    name: 'Đất trồng cây hàng năm khác',
    ma: 'HNK',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,240,180)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 14,
    name: 'Đất bằng trồng cây hàng năm khác',
    ma: 'BHK',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,240,180)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 15,
    name: 'Đất nương rẫy trồng cây hàng năm khác',
    ma: 'NHK',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,240,180)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 16,
    name: 'Đất lâm nghiệp',
    ma: 'LNP',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(170,255,50)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 17,
    name: 'Đất rừng sản xuất',
    ma: 'RSX',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(180,255,180)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 18,
    name: 'Đất có rừng sản xuất là rừng tự nhiên',
    ma: 'RSN',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(180,255,180)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 19,
    name: 'Đất có rừng sản xuất là rừng trồng',
    ma: 'RST',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(180,255,180)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 20,
    name: 'Đất đang được sử dụng để phát triển rừng sản xuất',
    ma: 'RSM',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(180,255,180)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 21,
    name: 'Đất rừng phòng hộ',
    ma: 'RPH',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(190,255,30)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 22,
    name: 'Đất có rừng phòng hộ là rừng tự nhiên',
    ma: 'RPN',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(190,255,30)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 23,
    name: 'Đất có rừng phòng hộ là rừng trồng',
    ma: 'RPT',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(190,255,30)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 24,
    name: 'Đất đang được sử dụng để phát triển rừng phòng hộ',
    ma: 'RPM',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(190,255,30)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 25,
    name: 'Đất rừng đặc dụng',
    ma: 'RDD',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(110,255,100)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 26,
    name: 'Đất có rừng đặc dụng là rừng tự nhiên',
    ma: 'RDN',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(110,255,100)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 27,
    name: 'Đất có rừng đặc dụng là rừng trồng',
    ma: 'RDT',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(110,255,100)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 28,
    name: 'Đất đang được sử dụng để phát triển rừng đặc dụng',
    ma: 'RDM',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(110,255,100)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 29,
    name: 'Đất nuôi trồng thủy sản',
    ma: 'NTS',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(170,255,255)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 30,
    name: 'Đất làm muối',
    ma: 'LMU',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,255,254)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 31,
    name: 'Đất nông nghiệp khác',
    ma: 'NKH',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(254, 255, 180)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 32,
    name: 'Đất phi nông nghiệp',
    ma: 'PNN',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 255, 100)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 33,
    name: 'Đất chuyên dùng',
    ma: 'CDG',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 160, 170)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 34,
    name: 'Đất Xây dựng cơ quan trụ sở',
    ma: 'TSC',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 35,
    name: 'Đất quốc phòng',
    ma: 'CQP',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 100, 80)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 36,
    name: 'Đất an ninh',
    ma: 'CAN',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 80, 70)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 37,
    name: 'Đất xây dựng công trình sự nghiệp',
    ma: 'DSN',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 160, 170)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 38,
    name: 'Đất xây dựng trụ sở của tổ chức sự nghiệp',
    ma: 'DTS',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 39,
    name: 'Đất xây dựng cơ sở văn hóa',
    ma: 'DVH',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 40,
    name: 'Đất xây dựng cơ sở dịch vụ xã hội',
    ma: 'DXH',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 41,
    name: 'Đất xây dựng cơ sở y tế',
    ma: 'DYT',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 42,
    name: 'Đất xây dựng cơ sở giáo dục và đào tạo',
    ma: 'DGD',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 43,
    name: 'Đất xây dựng cơ sở thể dục thể thao',
    ma: 'DTT',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 44,
    name: 'Đất xây dựng cơ sở khoa học và công nghệ',
    ma: 'DKH',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 45,
    name: 'Đất xây dựng cơ sở ngoại giao',
    ma: 'DNG',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 46,
    name: 'Đất xây dựng công trình sự nghiệp khác',
    ma: 'DSK',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 47,
    name: 'Đất sản xuất, kinh doanh phi nông nghiệp',
    ma: 'CSK',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 160, 170)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 48,
    name: 'Đất khu công nghiệp',
    ma: 'SKK',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 49,
    name: 'Đất cụm công nghiệp',
    ma: 'SKN',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 50,
    name: 'Đất khu chế xuất',
    ma: 'SKT',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 51,
    name: 'Đất thương mại, dịch vụ',
    ma: 'TMD',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 52,
    name: 'Đất cơ sở sản xuất phi nông nghiệp',
    ma: 'SKC',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 53,
    name: 'Đất sử dụng cho hoạt động khoáng sản',
    ma: 'SKS',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(205, 170, 205)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 54,
    name: 'Đất sản xuất vật liệu xây dựng, làm đồ gốm',
    ma: 'SKX',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(205, 170, 205)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 55,
    name: 'Đất có mục đích công cộng',
    ma: 'CCC',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 56,
    name: 'Đất giao thông',
    ma: 'DGT',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255, 170, 50)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 57,
    name: 'Đất thủy lợi',
    ma: 'DTL',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(170, 255, 255)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 58,
    name: 'Đất có di tích lịch sử – văn hóa',
    ma: 'DDT',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 59,
    name: 'Đất danh lam thắng cảnh',
    ma: 'DDL',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 60,
    name: 'Đất sinh hoạt cộng đồng',
    ma: 'DSH',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 61,
    name: 'Đất khu vui chơi, giải trí công cộng',
    ma: 'DKV',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 62,
    name: 'Đất công trình năng lượng',
    ma: 'DNL',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 63,
    name: 'Đất công trình bưu chính viễn thông',
    ma: 'DBV',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 64,
    name: 'Đất chợ',
    ma: 'DCH',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 65,
    name: 'Đất bãi thải, xử lý chất thải',
    ma: 'DRA',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(205,170, 205)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 66,
    name: 'Đất công trình công cộng khác',
    ma: 'DCK',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 67,
    name: 'Đất cơ sở tôn giáo',
    ma: 'TON',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 68,
    name: 'Đất cơ sở tín ngưỡng',
    ma: 'TIN',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,170, 160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 69,
    name: 'Đất nghĩa trang, nghĩa địa, nhà tang lễ, nhà hỏa táng',
    ma: 'NTD',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(210,210,210)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 70,
    name: 'Đất sông, ngòi, kênh, rạch, suối',
    ma: 'SON',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(160,255,255)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 71,
    name: 'Đất có mặt nước chuyên dùng',
    ma: 'MNC',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(180,255,255)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 72,
    name: 'Đất phi nông nghiệp khác',
    ma: 'PNK',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,170,160)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 73,
    name: 'Đất chưa sử dụng',
    ma: 'CSD',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,255,254)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 74,
    name: 'Đất bằng chưa sử dụng',
    ma: 'BSD',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,255,254)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 75,
    name: 'Đất đồi núi chưa sử dụng',
    ma: 'DCS',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(255,255,254)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 76,
    name: 'Núi đá không có rừng cây',
    ma: 'NCS',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(230,230,200)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 77,
    name: 'Đất có mặt nước ven biển (chỉ tiêu quan sát)',
    ma: 'MVB',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(180,255,255)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 78,
    name: 'Đất mặt nước ven biển nuôi trồng thủy sản',
    ma: 'MVT',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(180,255,255)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 79,
    name: 'Đất mặt nước ven biển có rừng',
    ma: 'MVR',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(180,255,255)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 80,
    name: 'Đất mặt nước ven biển có mục đích khác',
    ma: 'MVK',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: 'rgb(180,255,255)',
      borderColor: '#ff6b69',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 81,
    name: 'Đất trồng cây nông nghiệp lâu năm',
    ma: 'LNC',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: '#ffd2a0',
      borderColor: 'rgb(255,210,160)',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 82,
    name: 'Đang cập nhật',
    ma: 'COC',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: '#ffd2a0',
      borderColor: 'rgb(255,210,160)',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 83,
    name: 'Đất bãi bồi ven sông',
    ma: 'BCS',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: '#ffd2a0',
      borderColor: 'rgb(255,210,160)',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },

  // =======================================
  {
    id: 84,
    name: 'Đất trồng cây ăn quả lâu năm',
    ma: 'LNQ',
    styles: {
      width: 70,
      paddingVertical: 15,
      backgroundColor: '#ffd2a0',
      borderColor: 'rgb(255,210,160)',
      borderWidth: 0.5,
      borderRadius: 5,
      marginRight: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    id: 85,
    name: 'Đất sản xuất, kinh doanh phi nông nghiệp',
    ma: 'CDK',
  },
  {
    id: 86,
    name: 'Đất nông nghiệp (Đất ruộng 2 vụ)',
    ma: '2L',
  },
  {
    id: 87,
    name: 'Đất thổ cư gồm đất ở và đất vườn, ao',
    ma: 'T',
  },

  {
    id: 88,
    name: 'Đất trồng cây lâu năm khác',
    ma: 'LNK',
  },
  {
    id: 89,
    name: 'Hg/b - Đất bằng chưa sử dụng',
    ma: 'Hg/',
  },

  {
    id: 90,
    name: 'Đất giao thông',
    ma: 'GT',
  },

  {
    id: 91,
    name: 'Đất xây dựng trụ sở cơ quan',
    ma: 'CD',
  },
  {
    id: 91,
    name: 'Đất xây dựng',
    ma: 'XD',
  },
  {
    id: 92,
    name: 'Lua',
    ma: 'L',
  },
  {
    id: 93,
    name: 'Đất trồng cây công nghiệp lâu năm',
    ma: 'CN',
  },
  {
    id: 94,
    name: 'Tho cu vuon',
    ma: 'T.V',
  },
  {
    id: 95,
    name: 'Dất bằng chưa sử dụng',
    ma: 'Hg/b ',
  },

  {
    id: 97,
    name: 'đất trồng cây lâu năm khác',
    ma: 'b2',
  },
  {
    id: 96,
    name: 'Dất chuyên mầu và cây công nghiệp hàng năm',
    ma: 'm',
  },

  {
    id: 98,
    name: 'đất trồng lúa',
    ma: 'TL',
  },

  {
    id: 99,
    name: 'đất trồng cây hàng năm',
    ma: 'DM',
  },

  {
    id: 100,
    name: 'đất bằng chưa sử dụng',
    ma: 'b',
  },
  {
    id: 101,
    name: 'loại đất cây hàng năm khác(thuộc nhóm đất nông nghiệp)',
    ma: 'B2',
  },
  {
    id: 102,
    name: 'loại đất cây hàng năm khác(thuộc nhóm đất nông nghiệp)',
    ma: 'T1',
  },
];

export const AUTH_TOKEN_EXPIRATION = '15d';

export const OTP_VERIFY_PHONE_PREFIX = 'OTP_VERIFY_PHONE_123456789';
export const OTP_VERIFY_EMAIL_PREFIX = 'OTP_VERIFY_EMAIL_123456789';
export const OTP_RESET_PASSWORD_PREFIX = 'OTP_VERIFY_EMAIL_123456789';
